[package]
name = "zarrs-ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zarrs = "0.11.6"
serde_json = "1.0"
inquire = "0.6.2"
walkdir = "2"