[package]
name = "zarrs-ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zarrs = {path="../zarrs/"}
inquire = "0.6.2"